; WACSA Configuration

[CallbackAPI]
; Define your API Destination and Credentials for receive the status callback from wacsa. example "http://192.168.100.81:8090/api/notifier"
; IMPORTANT! Destination API must have Content-Type HEADER : "application/json"
MessageStatusEndpoint=
; Define your API Destination and Credentials for receive the incoming message callback from wacsa. example "http://192.168.100.81:8090/api/incoming"
; IMPORTANT! Destination API must have Content-Type HEADER : "application/json"
MessageIncomingEndpoint=
; Define your api auth name for securing while wacsa give callback request with Authorization Key Name Headers like "secretkey". default: "null"
AuthKeyName=
; Define your api auth key for securing while wacsa give callback request with Authorization Key Value Headers like "abcdefg12345". default: "null"
AuthKeyValue=
; Define max retry of failed callback API from wacsa to your apps in Number. default : 3
RetryFailure=
; Define interval of failed callback API from wacsa to your apps in Seconds. default : 1
IntervalFailure=

[FileLocking]
; Maximal Retry For Received Log When File is Locked. default : 5
ReceivedLogMaxRetry=
; Retry Interval For Received Log When File is Locked in seconds. default : 1
ReceivedLogRetryInterval=

; Maximal Retry For Sent Log When File is Locked. default : 5
SentLogMaxRetry=
; Retry Interval For Sent Log When File is Locked in Seconds. default : 1
SentLogRetryInterval=

; Maximal Retry For Statistic Log When File is Locked. default : 5
StatisticLogMaxRetry=
; Retry Interval For Statistic Log When File is Locked in Seconds. default : 1
StatisticLogRetryInterval=

[FolderLog]
; Folder Location For Saving Received Log. default : "WACSA Installation Folder Ex : D\Irma\Utils\wacsa"
ReceivedLogFolder=
; Folder Location For Saving Sent Log. default : "WACSA Installation Folder Ex : D\Irma\Utils\wacsa"
SentLogFolder=
; Folder Location For Saving Statistic Log. default : "WACSA Installation Folder Ex : D\Irma\Utils\wacsa"
StatisticLogFolder=

[BackupLog]
; Backup Enabler For Received Log. default : true
ReceivedLogBackup=
; Backup Enabler For Sent Log. default : true
SentLogBackup=
; Backup Enabler For Statistic Log. default : true
StatisticLogBackup=

[ServerOptions]
; cors origin which IP Address or Domains can access this apps. default: "*" (that means all address can access this apps)
; if you want use multiple domain. input an array brace [] like ["http://csacomputer.com", "http://others.com"]
cors=
; port listener for this apps . default: 8008
port=
; attachment saving to Received Log enabler. default : true
attachment=
; this chrome location is important for enable send video from whatsapp csa. default: C:/Program Files/Google/Chrome/Application/chrome.exe
chrome=
; define your timeout if WA Client isn't exist in seconds. default : 30
timeout=10
; this headless is options for view or hidden browser from user. default: true
;headless=false
; this config above only for when WA Web not working purpose
headless=
; define windows position of browser x,y. default 0,0
;winPos=5000,0
; this config above only for when WA Web not working purpose
winPos=
; define windows size of browser width, height. default: 800,600
;winSize=1,1 
; this config above only for when WA Web not working purpose
winSize=
; turn off WA receivedLog (In this case, if was false, the file size will grow over time). default: false
disableReceivedLog=
; turn off WA sentLog scheme. default: false
disableSentLog=