; WACSA Configuration

[CallbackAPI]
; Define your API Destination and Credentials for receive the status callback from wacsa example "http://192.168.100.81:8090/api/notifier"
; IMPORTANT! Response Header must have Content-Type : "application/json"
MessageStatusEndpoint="http://192.168.100.81:8090/api/new_api"
MessageStatusAuth=
; Define your API Destination and Credentials for receive the incoming message callback from wacsa example "http://192.168.100.81:8090/api/incoming"
; IMPORTANT! Response Header must have Content-Type : "application/json"
MessageIncomingEndpoint="http://192.168.100.81:8090/api/new_api"
MessageIncomingAuth=

[FileLocking]
; Maximal Retry For Received Log When File is Locked. default : 5
ReceivedLogMaxRetry=
; Retry Interval For Received Log When File is Locked in seconds. default : 1
ReceivedLogRetryInterval=

; Maximal Retry For Sent Log When File is Locked. default : 5
SentLogMaxRetry=
; Retry Interval For Sent Log When File is Locked in Seconds. default : 1
SentLogRetryInterval=

; Maximal Retry For Statistic Log When File is Locked. default : 5
StatisticLogMaxRetry=
; Retry Interval For Statistic Log When File is Locked in Seconds. default : 1
StatisticLogRetryInterval=

[FolderLog]
; Folder Location For Saving Received Log. default : "WACSA Installation Folder Ex : D\Irma\Utils\wacsa"
ReceivedLogFolder=
; Folder Location For Saving Sent Log. default : "WACSA Installation Folder Ex : D\Irma\Utils\wacsa"
SentLogFolder=
; Folder Location For Saving Statistic Log. default : "WACSA Installation Folder Ex : D\Irma\Utils\wacsa"
StatisticLogFolder=

[BackupLog]
; Backup Enabler For Received Log. default : true
ReceivedLogBackup=
; Backup Enabler For Sent Log. default : true
SentLogBackup=
; Backup Enabler For Statistic Log. default : true
StatisticLogBackup=

[ServerOptions]
; cors origin which IP Address or Domains can access this apps. default: "*" (that means all adress can access this apps)
cors=
; port listener for this apps . default: 8000
port=
; attachment saving to Received Log enabler. default : true
attachment=
; this chrome location is important for enable send video from whatsapp csa. default: C:/Program Files/Google/Chrome/Application/chrome.exe
chrome=